export const productsColumns = [
  {
    name: 'showProduct',
    label: 'подробно',
    align: 'center',
    field: 'showProduct',
  },
  {
    name: 'addToOrder',
    label: 'Добавить в заказ',
    align: 'center',
    field: 'addToOrder',
  },
  {
    name: 'preview_image',
    label: 'Эскиз',
    align: 'center',
    field: 'preview_image',
  },
  {
    name: 'id',
    label: 'id в БД',
    align: 'center',
    field: 'id',
    sortable: true,
  },
  {
    name: 'title',
    label: 'Продукт',
    align: 'center',
    field: 'title',
    sortable: true,
  },
  {
    name: 'description',
    label: 'Описание',
    align: 'center',
    field: 'description',
    sortable: true,
  },
  {
    name: 'publisher',
    label: 'Издатель',
    align: 'center',
    field: 'publisher',
    sortable: true,
  },
  {
    name: 'release_date',
    label: 'Дата выхода',
    align: 'center',
    filed: 'release_date',
    sortable: true,
  },

  {
    name: 'price',
    label: 'Цена',
    align: 'center',
    filed: 'price',
  },
  {
    name: 'amount',
    label: 'Количество на складе',
    align: 'center',
    filed: 'amount',
  },
  {
    name: 'is_published',
    label: 'Опубликован',
    align: 'center',
    filed: 'is_published',
  },
  {
    name: 'destroy',
    label: 'удалить',
    align: 'center',
    field: 'destroy',
  },
]
