export const usersColumns = [
  {
    name: 'show',
    label: 'Подробнее',
    align: 'center',
    field: 'show',
  },
  {
    name: 'id',
    label: 'id в БД',
    align: 'center',
    field: 'id',
    sortable: true,
  },
  {
    name: 'avatar',
    label: 'avatar',
    align: 'center',
    field: 'avatar',
  },
  {
    name: 'email',
    label: 'email',
    align: 'center',
    field: 'email',
    sortable: true,
  },
  {
    name: 'name',
    label: 'Имя',
    align: 'center',
    field: 'name',
  },
  {
    name: 'surname',
    label: 'Фамилия',
    align: 'center',
    field: 'surname',
  },
  {
    name: 'patronymic',
    label: 'Отчество',
    align: 'center',
    field: 'patronymic',
  },
  {
    name: 'age',
    label: 'Возраст',
    align: 'center',
    field: 'age',
    sortable: true,
  },
  {
    name: 'address',
    label: 'Адрес',
    align: 'center',
    field: 'address',
  },
  {
    name: 'phoneNumber',
    label: 'Телефон',
    align: 'center',
    field: 'phoneNumber',
  },
  {
    name: 'destroy',
    label: 'удалить',
    align: 'center',
    field: 'destroy',
  },
]
